package com.gmail.jorgegilcavazos.ballislife.features.model

data class GameV2(val arena: String,
                  val awayTeamAbbr: String,
                  val awayTeamCity: String,
                  val awayTeamId: String,
                  val awayTeamKey: String,
                  val awayTeamNickname: String,
                  val awayTeamScore: String,
    val broadcasters: Map<String, MediaSource>,
                  val city: String,
                  val date: String,
                  val gameClock: String,
                  val gameStatus: String,
                  val homeTeamAbbr: String,
                  val homeTeamCity: String,
                  val homeTeamId: String,
                  val homeTeamKey: String,
                  val homeTeamNickname: String,
                  val homeTeamScore: String,
                  val id: String,
                  val periodName: String,
                  val periodStatus: String,
                  val periodValue: String,
                  val time: String,
                  val timeUtc: Long,
                  val totalPeriods: String)